reconnection_delay: 2
enable_pointcloud : true
enable_pointcloud_xyzrgb : true
enable_d2c_viewer: false
number_of_devices : 2
enable_reconfigure: false
color_width : 160
color_height: 120
color_fps: 30
enable_color: false
depth_width : 160
depth_height: 120
depth_fps: 30
enable_depth: true
depth_align : false
ir_width : 160
ir_height: 120
ir_fps: 30
enable_ir: false
publish_tf : true
tf_publish_rate: 40.0
depth_scale : 1
color_roi_x: -1
color_roi_y : -1
color_roi_width: -1
color_roi_height : -1
depth_roi_x: -1
depth_roi_y : -1
depth_roi_width: -1
depth_roi_height : -1
color_depth_synchronization : false
use_uvc_camera : false
uvc_vendor_id : 0x2bc5
uvc_product_id: 0x00
uvc_camera_format: "mjpeg"
uvc_flip: false
keep_alive : false
keep_alive_interval : 15
uvc_retry_count : 100
oni_log_level : "verbose" # verbose/ info /warning/ error /none
oni_log_to_console: false
oni_log_to_file : false